doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
        types:
            productId: App\Catalog\Infrastructure\Persistence\DBAL\ProductIdType
            sellerId: App\Seller\Infrastructure\Persistence\DBAL\SellerIdType
            sellerProductId: App\Seller\Infrastructure\Persistence\DBAL\SellerProductIdType
            cartId: App\Customer\Infrastructure\Persistence\DBAL\CartIdType
            cartItemId: App\Customer\Infrastructure\Persistence\DBAL\CartItemIdType
            customerId: App\Customer\Infrastructure\Persistence\DBAL\CustomerIdType

            stock: App\Seller\Infrastructure\Persistence\DBAL\StockType
            amount: App\Shared\Infrastructure\Persistence\DBAL\AmountType
            email: App\Shared\Infrastructure\Persistence\DBAL\EmailType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Catalog:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Catalog/Infrastructure/Persistence/Model'
                prefix: 'App\Catalog\Domain\Model'
                alias: App\Catalog\Domain\Model
            Seller:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Seller/Infrastructure/Persistence/Model'
                prefix: 'App\Seller\Domain\Model'
                alias: App\Seller\Domain\Model
            Customer:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Customer/Infrastructure/Persistence/Model'
                prefix: 'App\Customer\Domain\Model'
                alias: App\Customer\Domain\Model
